### ISSUE TITLE
Add demographics to mentor model

### ISSUE THREAD

**Issue by karbassi** [CoderDojoChi/coderdojochi#386] opened 2016-08-12 04:26 UTC
Add the following to mentor model
- [x] `birthday` (**required**, date) - for age demographics
- [x] `gender` (**required**, text field) - for gender demographics
- [x] `race_ethnicity` (**required**, M2M?) - for race demographics
- [x] `shirt_size`(**required**)
- [x] `work_place` (optional, textfield) - for future job board
- [x] `phone` (optional, textfield) - for contacting, later
- [x] `home_address` (optional, textfield) - for mentor reach demographic

Add to mentor profile page.
- [x] `birthday` should be date picker
- [x] `gender` should be text field
- [x] `race_ethnicity` should be a multi-checkbox
- [x] `work_place` should be a text field
- [x] `phone` should be validated field
- [x] `home_address` should be a google api search

**Comment by MVanderwood** [comment] 2016-10-03 22:05
This is a duplicate of #343. We should keep this one though, as it is more descriptive.

**Closed** 2018-08-15 23:12 UTC
Labels: enhancement
