### ISSUE TITLE
Remove email addresses from url and alternate text of volunteer images

### ISSUE THREAD

**Issue by dlarosa** [CoderDojoChi/coderdojochi#238] opened 2015-09-26 16:17 UTC
It makes email addresses googable and public.

```
<img src="http://coderdojochi.org/media/avatars/test%40gmail.com/resized/175/image.jpg" alt="test@gmail.com" width="175" height="175">
```

**Comment by karbassi** [comment] 2015-09-27 00:44
This is because of django-avatar. There is a pull request that's open, but not merged.

https://github.com/grantmcconnaughey/django-avatar/pull/105

We might have to find a different avatar package. Any suggestions @bkellgren @dlarosa

**Comment by karbassi** [comment] 2016-04-30 17:35
Duplicate of #282

**Closed by karbassi** 2016-04-30 17:35 UTC
Labels: in progress
