### ISSUE TITLE
Increase maximum allowed avatar image size

### ISSUE THREAD

**Issue by bkellgren** [CoderDojoChi/coderdojochi#241] opened 2015-10-27 00:54 UTC
Default is 1MB, I'm thinking maybe update to 2MB then resizing to a lower resolution on the server if possible.

https://django-avatar.readthedocs.org/en/latest/

**Comment by karbassi** [comment] 2016-04-30 17:35
Duplicate of #282

**Closed by karbassi** 2016-04-30 17:35 UTC
Labels: in progress
